activation: silu
aggr: add
atom_filter: -1
attn_activation: silu
batch_size: 16
coord_files: null
cutoff_lower: 0.0
cutoff_upper: 5.0
dataset: PCQM4MV2_Force
dataset_arg: null
dataset_root: /data2/SKData/DenoisingData/pcq
derivative: false
distance_influence: both
distributed_backend: ddp
early_stopping_patience: 150
ema_alpha_dy: 1.0
ema_alpha_y: 1.0
embed_files: null
embedding_dimension: 128
energy_files: null
energy_weight: 0.0
force_files: null
force_weight: 1.0
inference_batch_size: 70
load_model: null
log_dir: experiments/
lr: 0.0004
lr_schedule: cosine
lr_factor: 0.8
lr_min: 1.0e-07
lr_patience: 15
lr_warmup_steps: 10000
lr_cosine_length: 240000
max_num_neighbors: 32
max_z: 100
model: equivariant-transformerf2d_org
neighbor_embedding: true
ngpus: -1
num_epochs: 16
num_steps: 240000
num_heads: 8
num_layers: 6
num_nodes: 1
num_rbf: 32
num_workers: 16
output_model: Scalar
precision: 32
prior_model: null
rbf_type: expnorm
redirect: false
reduce_op: add
save_interval: 1
splits: null
standardize: false
test_interval: 1
test_size: 100
train_size: null
trainable_rbf: false
val_size: 100
weight_decay: 0.0
output_model_ff_noise: Scalar
output_model_noise: VectorOutput
# bond_length_scale: 0.04
# angle_noise_scale: 0.09
# dihedral_angle_noise_scale: 2

use_edge_feat: true
md17: true

addh: true
composition: true
no_target_mean: false
sdf_path: 'mol_iter_all.pickle'

denoising_weight: 1.0
denoising_only: true
layernorm_on_vec: null
wandb_notes: ""
job_id: auto

derivative_var: 1
use_force_param: 1
add_ring_noise: false

dihedral_angle_noise_scale: 1 
angle_noise_scale: 0.129 
bond_length_scale: 0.058
nt_noise_scale: 0.18 
sample_num: 128
frad_guassian_scale: 0.04